### ISSUE TITLE
Allow the content of %text% and %html% to be stored in a stacks property/var

### ISSUE THREAD

**Issue by designdisorder** [yourhead/s3#112]
To allow for an easier handling of the content entered into a %text% or %html% stack allow the content to be stored into a stacks property/var for later reuse. Right now this is only possible by marshaling the content via some custom generated JS or PHP code which makes templates more complex and error prone. As markup we could use something like %text -var=„foobar“% or %text -id=„foobar“% to generate a stacks var/property

**Comment by yourhead** [comment]
this is a really good idea. it is unfortunately non-trivial to implement. as it would need to dynamically change properties of one thing (the stack) with the content of another (the text content node). i do this (in a very limited form) with image transforms -- but it's nothing like the more generalized form that you propose here.

**Comment by yourhead** [comment]
i think this will happen...   i'm just not sure i'll have time to squeeze it in for 3.0

**Comment by yourhead** [comment]
i've been working on things surrounding this. and unfortunately the consequences of a change that involves pulling the content of a stack and using it in other places -- like a separate variable in a different file -- has kind of profound impact on how things are coached and the order of processing.

we're already suffering from odd corner case behaviors here in image transforms -- those, however are benefited because images themselves are immutable objects -- text is not.

i'm afraid, i think this is outside of the feasibility of the stacks templating system.  i think we'll have to wait for stacks to grow up and use a compiled template language (handlebars) -- and that's more in the "someday" category.
