### ISSUE TITLE
keybinding: cannot navigate library groups with arrow keys

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#148]
Just realized this _is_ possible, but navigating to the next group automatically moves the focus to the contents of that group. In order to navigate via an arrow key again, the user must click on the group icon again to make it the focus.

**Comment by yourhead** [comment]
it's actually purposeful that the first responder jumps back to the contents immediately -- i figured you'd be navigating those more often than the library groups -- since there are so few.

that said, i think it needs work. there seems to be a regression that is causing the arrow keys to not work anywhere (maybe not in your version -- but in mine for sure)

and i think maybe we could do something non-standard to navigate the library -- how 'bout command-arrow
