### ISSUE TITLE
there is no method to delete partials from the main library partials group

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#150]
Not sure if this is by design. I would expect it to be possible, even if it's not advisable.

**Comment by yourhead** [comment]
this is intentional. partials are a representation of what is in your document. when you delete them from your document, they'll leave your library too.

**Comment by NimbleHost** [comment]
in a13 when the last instance of a particular partial is deleted, the partials library group is not immediately updated (even upon saving the document). In other words, that partial remains in the library, even though no pages in the document use that partial. Closing the document, or restarting RW, does reflect that the deleted partial is no longer present in the library.

to be clear, i think this is a good thing and shouldn't be changed (just in case the user decides they want to use that partial later, before closing the document), but based on what you mentioned earlier, i would expect the library to be updated immediately when all instances of the partial are removed.

**Comment by yourhead** [comment]
i wouldn't want to clear it from the library right away.  because i can see a user creating a partial, then deciding they want it on another page. so they:
1. delete the partial (the last one)
2. switch pages
3. drag the partial from the library

in other words the library maintains a bit of buffer for temporarily unused items.  and i think that's probably a good thing.

that said, there is one UX thing that probably needs addressing:  when the user removes the last partial there should probably be some sort of warning that the partial is going to get vaporized as soon as they close the document.

**Comment by NimbleHost** [comment]
agreed, having a warning would be really nice, if possible.
