### ISSUE TITLE
setting for the max number of instances in a single parent

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#160]
changing this request to set the maximum number of times a stack can be used within a single parent. this is more feasible. see below for detail.

> original:  This issue is in reference to #159. In case there are situations where limiting the number of times a stack can be added to a page is needed, it would be nice to have an option to specify how many times a stack can be used on a single page.

**Comment by yourhead** [comment]
It turns out that this is really hard to do.  And implies some strange UI.

a good example:
imagine a site with 2 pages: page1 and page2
now imagine a stack (stackA) that has a page-count-limit of 1-stack-per-page.

first we add stackA to page1.
then we add a partial (partialB) to page1.

on page two we also add partialB.

now we edit partialB and add stackA.

this means there are now two instances of stackA on page1. this violates our rule.  however it is very difficult to discover this violation -- we have to traverse the entire site looking for violations or keep a synced violation index in memory.

and when we need to report this error to the user, it is even more difficult.  changes to partials can potentially cause dozens of violations -- there is no easy way to help the user understand why the addition of stackA was prevented.

**Comment by yourhead** [comment]
I think we can, perhaps, change this feature request to something that's a bit more feasible. we can prevent a stack from being used more than n-times in a specific hierarchy. this is far more feasible.

**Comment by NimbleHost** [comment]
Sounds like a good compromise. :-)

**Comment by joeworkman** [comment]
I would be happy with that

**Comment by yourhead** [comment]
i have a feeling this is already implemented, just not currently documented.

**Comment by yourhead** [comment]
I've finished this one. Could still use a better UI though.

in beta 9: `-maxChildren=n` will limit the number of children you can drag into the stack. it will also remove the + button once the max is reached.

I'll add a new enhancement request to the list for implementing a more user-friendly disabled button / disabled menu. but i'm pushing that out to 4.0

**Comment by yourhead** [comment]
documentation:  http://api.yourhead.com/templates/slice/
