### ISSUE TITLE
Link to resources is adding spaces

### ISSUE THREAD

**Issue by ghost** [yourhead/s3#244]
%[if !edit]%a href="%rapidweaverAssetPath%/%[endif]%%text="image.jpg"%%[if !edit]%">%[endif]%something</a

Creates:
a href="resources/ image.jpg ">something</a

Expected:
a href="resources/image.jpg">something</a

The extra spaces either side of image name stop it from rendering..

**Comment by ghost** [comment]
Gist: 
https://gist.github.com/yuzoolcode/09fef3002d703e6f0055

**Comment by yourhead** [comment]
this will be fixed in beta 2. the default behavior is zero whitespace around text.

however, there is one caveat:  if the user un-checks this setting

Stacks Prefs > HTML > Remove: Whitespace in HTML

then the HTML is generated with more whitespace and comments -- which might impact the behavior you're looking for.

hopefully this is all a moot point, since you've already updated your stack.  ;-)

**Comment by ghost** [comment]
Awesome - sounds good to me and thanks for your help on this and looking into it. Great stuff
