### ISSUE TITLE
Library CSS files need to be loaded before the stack_page.css files

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#288]
Library CSS files need to be loaded before the stack_page_*.css files. This is so that they are properly set the default styles and they stacks css properly overrides it.

**Comment by yourhead** [comment]
i would tend to the the opposite would be true. can you provide a concrete example where this is a problem?

**Comment by joeworkman** [comment]
Screenshot: http://jwurl.net/1f88SPz

The opposite makes sense for JS but not CSS. I have migrated Foundation to use the new Libraries and I am loading foundation.css this way. If you look at this screenshot, the window on the left is loading foundation.css via Libraries and the one on the left is loading it from the theme. 

The only difference is that libraries is loading the foundation.css file after/before the stacks_page.css file. Since the foundation.css defines default styles, it should be loaded first. 

I will not be able to use this at all as it is right now.

**Comment by yourhead** [comment]
this seems crazy to me. this means that your CSS relies on stacks.css to overload some of the things you do.  why?
why not simply set things the way you want?

without more specific information i can only say this seems bassackwards and close this bug.

but i don't think discussing this at a 10,000 ft. level is going to get us anywhere. looking at all of stacks and all of foundation involves thousands of styles and dozens of overrides and a bajillion CSS scope rules. that's too much to think about.

 i think we need to take one specific style, look at how it is defined in each file and the end result. find out specifically why its turning out that way and attack that problem.

can you take your example and just follow the font color difference of the button.  i think with a specific single example we can understand the problem and find a solution much more easily.

**Comment by doobox** [comment]
I have to agree with Joe here. This would be helpful for any CSS framework, else we'd need to start pulling the framework to bits, removing any styles that we want the user to choose specifically. Else the framework would just overrule the users style choice in the red css (image).
![css-positions](https://cloud.githubusercontent.com/assets/1026876/8736822/dba55986-2c13-11e5-835b-3288b60d4921.png)

**Comment by yourhead** [comment]
i completely reject this. seems insane to me.

example. with steps. and specifics. or GTFO.

**Comment by atavernor** [comment]
Surely this is a simple case of the CSS order of priority.

Because the user has the option to change styles at a "page" or framework level via a stack rather than theme control  (in the case of Foundation, the Site Styles stack) then necessarily the resultant CSS cannot be scoped to that stack as would normally be the case for a stack setting.

So in the case of the button, the user will define the primary text color via a Site Styles stack but it must be applied to all text elements on the page (including that button), unless subsequently over ridden for individual stacks.  This step is directly analogous to setting the primary color in the Foundation SCSS if hand coding a site.

But in the RW environment we cannot directly edit the framework CSS and so it must be loaded in a generic form. If this occurs after the above step it will obviously over ride those settings. This is the crucial difference.

The only way around this would be to have `!important`'s on everything defined at a page (site styles) level thus precluding the user from styling individual stacks with custom settings. 

So specifically:

#### With framework loaded first;

`body{color:#222}`  Defined by Zurb  

`body{color:#ccc}`  Defined in site styles by user for all generic text including buttons

`button{color:#ffccaal}` User over rides an individual button 

##### Result: Behaves as expected.

---

#### With framework loaded after stacks css and no `!important`'s:

`body{color:#ccc}`  Defined in site styles by user for all generic text including buttons

`body{color:#222}`  Defined by Zurb  

`button{color:#ffccaal}` User over rides an individual button 

##### Result:  the User gets Zurb's choice of colors for everything except stacks that are individually styled.

---

#### With framework loaded after stacks css and using  `!important`'s on the Site Styles settings;

`body{color:#ccc!important}`  Defined in site styles by user for all generic text including buttons

`body{color:#222}`  Defined by Zurb  

`button{color:#ffccaal}` User over rides an individual button 

##### Result: Page styles work as expected but individual stacks are not styled as per the user settings. And we have hundreds of `!important`'s everywhere

**Comment by yourhead** [comment]
ah. makes perfect sense. i see. the goal is not to load after the general stacks css, but the css of the specific stack. i think i got lost in the crazy of the terminology. thanks @atavernor

**Comment by joeworkman** [comment]
YES! The professor strikes again!

**Comment by joeworkman** [comment]
When I got home and read your statement about `stacks.css`, I thought that there was some misunderstanding... When I was referring to the `stacks_page*.css` file, I meant the css that contains the page and each scoped styles for stacks.

**Comment by joeworkman** [comment]
In the below example, the foundation.css file is loaded via the libraries API... 

Current Output:

```
<link rel='stylesheet' type='text/css' media='all' href='/rw_common/plugins/stacks/stacks.css' />
<link rel='stylesheet' type='text/css' media='all' href='index_files/stacks_page_page0.css' />
<link rel="stylesheet" type="text/css" media="all" href="/rw_common/plugins/stacks/foundation.css" />
```

Desired Output:

```
<link rel='stylesheet' type='text/css' media='all' href='/rw_common/plugins/stacks/stacks.css' />
<link rel="stylesheet" type="text/css" media="all" href="/rw_common/plugins/stacks/foundation.css" />
<link rel='stylesheet' type='text/css' media='all' href='index_files/stacks_page_page0.css' />
```

or

```
<link rel="stylesheet" type="text/css" media="all" href="/rw_common/plugins/stacks/foundation.css" />
<link rel='stylesheet' type='text/css' media='all' href='/rw_common/plugins/stacks/stacks.css' />
<link rel='stylesheet' type='text/css' media='all' href='index_files/stacks_page_page0.css' />
```

I am indifferent if the library is loaded before or after stacks.css. As long as it loads before he stacks_page_page0.css file, I am happy.

**Comment by joeworkman** [comment]
I am just curious as to how Stacks will ultimately resolve which stack to pull the foundation.css file from. The first stack on the page? 

Example: Let's say that my Foundation stacks load a certain version of foundation.css and another developer has a different version of foundation.css that ships with his stack using the same `filename` and `name` attributes.

**Comment by yourhead** [comment]
@atvernor showed a specific style. really that's all i needed to see.

dealing with things at the macro level makes for too many ambiguities. and in this case the ambiguities lead to misunderstanding.

**Comment by yourhead** [comment]
it's up to the developer to ensure that the various copies of the library are identical. if they are not, then the copy that is included is undefined. it may change from publish to publish

**Comment by yourhead** [comment]
if there is no objection, this is the order that will be in the next build:

// css  
stacks site css
named css libraries
stacks page css

// js libraries
jQuery
font Awesome
jQuery ui
mootools
named js libraries

// other head content
page head above 
page js and/or jquery closures
meta tags
page head below
