### ISSUE TITLE
undo behavior strange with partials

### ISSUE THREAD

**Issue by yourhead** [yourhead/s3#296]
Resubmitted Observation: Undo doesnt see Partials, if you do 10 actions, make a Partial and do 10 actions within that AND then undo 10 times its the 10 actions prior to making the partial that gets undone.

**Comment by yourhead** [comment]
This was submitted without specifics from a customer. I'm not 100% sure I grok what they mean, but partial undo support is 1000% better -- so hopefully it's a done deal.

**Comment by FichtMedia** [comment]
If I select a stack and then accidentally click on "Partials" I immediately get into the Partials editor which I can only exit by clicking on "Done". This way I have converted the stack into a Partials and I don't see any way to undo this step. What about a 2nd button "Cancel" next to the "Done" button, so that I can cancel the conversion of the selected stack into a partial? Or at least a functioning "Undo" to undo the Partial-creation.

**Comment by FichtMedia** [comment]
Hmm, for me no change with beta 5. Still the same weired behaviour with showing all Media files when clearing the search field ...

Closed #296.

**Comment by yourhead** [comment]
I'm not sure what the search field has to do with this bug.  Perhaps you can explain a bit more what I should do to see what you're seeing.

This is what I do:
1. Click on a Stack.
2. Click on the Partial button.
3. Click Done.
4. Select Undo from the Edit menu.

The result is the layout is back to the place I started.  This is the expected result.

**Comment by FichtMedia** [comment]
Hi Isaiah, you're right of course, sorry.  I've mangled two issues here. The undo partial subject is actually solved. Works just fine now. :-)  The other thing I mentioned (showing all Media files when clearing the search field) is still there, but has nothing to do with this bug and therefor doesn't belong in this thread. Sorry.
