### ISSUE TITLE
Click Stack > Show CP Sidebar > Preview > Change to Popover = 'RW Crash'

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#329]
Click Stack > Show CP Sidebar > Preview > Change to Popover = 'RW Crash'

Well doesn't really crash but RW pops up the 'Something went wrong...' message.

Doing it the other way:
Click Stack > Show CP Sidebar > Change to Popover > Preview = Hides the Popover > but no crash.

Guess it's only possible to change settings in the Stacks CP Sidebar when previewing a RW doc > but not when Sidebar goes Popover. 

But no problem... changing stacks settings when previewing a RW document will save a lot of clicks and probably boost WorkFlowSpeed by 300%

**Comment by yourhead** [comment]
I'm afraid I can't duplicate this one.  Can you tell me what "CP Sidebar" is and what you click/do/type to "Show CP Sidebar".

If this involves the state of the sidebar then it is very likely the size of your display, if the window fills the screen, and if the screen is in retina mode are all vital pieces of info.

**Comment by yourhead** [comment]
Also if there is a crash (or the Something went wrong) -- the crash report (obtained by clicking the info "i" button is very very very helpful.

**Comment by yourhead** [comment]
ok, without further info, there's nothing really i can do here. i don't understand. i need some more specific details of how to duplicate this in order to be able to fix it.

**Comment by DeFliGra** [comment]
Here's a little Spielberg trying to specify the details.

It's nothing to do with the specific stack used in the demo. It will happens with a simple text stack as well.
I can replicate this on both my 27" iMac & my 13" Macbook Air. Same behavior.

https://db.tt/AwKGSxLa

**Comment by girlcarew** [comment]
Exceptions report from my reproduction of this bug.

---1---
Incident Identifier: 38690AA9-F09A-4913-B4A4-4B2CFE55D738
CrashReporter Key:   TODO
Hardware Model:      MacBookAir4,1
Process:         RapidWeaver 6 [16711]
Path:            /Applications/RapidWeaver 6.app/Contents/MacOS/RapidWeaver 6
Identifier:      com.realmacsoftware.rapidweaver6
Version:         14912
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:         2015-07-20 16:01:15 +0000
OS Version:        Mac OS X 10.10.3 (14D136)
Framework Version: 1.0.3
Report Version:    106

Exception Type:  SIGTRAP
Exception Codes: TRAP_TRACE at 0x10541cb11

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSPopover showRelativeToRect:ofView:preferredEdge:]: view has no window. You must supply a view in a window.'

Last Exception Backtrace:
0   com.apple.CoreFoundation            0x00007fff8ee80024 __exceptionPreprocess + 148
1   libobjc.A.dylib                     0x00007fff8846f76e objc_exception_throw + 43
2   com.apple.CoreFoundation            0x00007fff8ee7feed +[NSException raise:format:] + 205
3   com.apple.AppKit                    0x00007fff896c2043 -[NSPopover showRelativeToRect:ofView:preferredEdge:] + 159
4   YHStacksPlugin                      0x000000010a344d03 -[YHStacksDocument showInfoPopover] + 243
5   YHStacksPlugin                      0x000000010a35aa6b -[YHBottomInfoToolbarView onPopover:] + 75
6   libsystem_trace.dylib               0x00007fff919facd7 _os_activity_initiate + 75
7   com.apple.AppKit                    0x00007fff8967bfb1 -[NSApplication sendAction:to:from:] + 452
8   com.apple.AppKit                    0x00007fff89691a46 -[NSControl sendAction:to:] + 86
9   com.apple.AppKit                    0x00007fff89691962 __26-[NSCell _sendActionFrom:]_block_invoke + 131
10  libsystem_trace.dylib               0x00007fff919facd7 _os_activity_initiate + 75
11  com.apple.AppKit                    0x00007fff896918bf -[NSCell _sendActionFrom:] + 144
12  libsystem_trace.dylib               0x00007fff919facd7 _os_activity_initiate + 75
13  com.apple.AppKit                    0x00007fff89722b8e -[NSButtonCell performClick:] + 1027
14  YHStacksPlugin                      0x000000010a2e160a -[YHToolbarItem view:didMouseUp:] + 266
15  YHStacksPlugin                      0x000000010a308e1a -[YHToolbarItemView mouseUp:] + 202
16  com.apple.AppKit                    0x00007fff89bf4e57 -[NSWindow _reallySendEvent:isDelayedEvent:] + 648
17  com.apple.AppKit                    0x00007fff89587d76 -[NSWindow sendEvent:] + 470
18  com.apple.AppKit                    0x00007fff89584312 -[NSApplication sendEvent:] + 2504
19  com.apple.AppKit                    0x00007fff894adc68 -[NSApplication run] + 711
20  com.apple.AppKit                    0x00007fff8942a354 NSApplicationMain + 1832
21  libdyld.dylib                       0x00007fff867c35c9 start + 1

Thread 0:
0   libobjc.A.dylib                     0x00007fff884620ee objc_msgSend + 46
1   com.apple.AppKit                    0x00007fff8945cd12 -[NSView _wantsPrepareContentRect] + 53
2   com.apple.AppKit                    0x00007fff8945cc9c -[NSView _wantsToPrefetchContent] + 185
3   com.apple.AppKit                    0x00007fff89486042 -[NSView setFrameSize:] + 1954
4   com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
5   com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
6   com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
7   com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
8   com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
9   com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
10  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
11  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
12  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
13  com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
14  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
15  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
16  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
17  com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
18  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
19  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
20  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
21  com.apple.AppKit                    0x00007fff8974dabd -[NSBox _tile:] + 236
22  com.apple.AppKit                    0x00007fff89755d04 -[NSBox setFrameSize:] + 109
23  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
24  com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
25  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
26  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
27  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
28  com.apple.AppKit                    0x00007fff895aef6b -[NSSplitView _setFrameOrAlignmentRect:ofSubview:] + 196
29  com.apple.AppKit                    0x00007fff895fac4c -[NSSplitView adjustSubviews] + 6970
30  com.realmacsoftware.rapidweaver6    0x0000000104bd3ae6 0x104b95000 + 256742
31  com.apple.AppKit                    0x00007fff895f8dfc -[NSSplitView resizeSubviewsWithOldSize:] + 1001
32  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
33  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
34  com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
35  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
36  com.apple.AppKit                    0x00007fff89485f01 -[NSView setFrameSize:] + 1633
37  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
38  com.apple.AppKit                    0x00007fff8974dabd -[NSBox _tile:] + 236
39  com.apple.AppKit                    0x00007fff89755d04 -[NSBox setFrameSize:] + 109
40  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
41  com.apple.AppKit                    0x00007fff894f128f -[NSView resizeWithOldSuperviewSize:] + 694
42  com.apple.AppKit                    0x00007fff894efbdc -[NSView resizeSubviewsWithOldSize:] + 317
43  com.apple.AppKit                    0x00007fff89487102 NSViewLevelLayout + 165
44  com.apple.AppKit                    0x00007fff895f81a4 -[NSView _layoutSubtreeWithOldSize:] + 373
45  com.apple.AppKit                    0x00007fff89485ee5 -[NSView setFrameSize:] + 1605
46  com.apple.AppKit                    0x00007fff89485083 -[NSView setFrame:] + 464
47  com.realmacsoftware.rapidweaver6    0x0000000104bd3940 0x104b95000 + 256320
48  com.apple.AppKit                    0x00007fff895f8dfc -[NSSplitView resizeSubviewsWithOldSize:] + 1001
49  com.apple.AppKit                    0x00007fff89487102 NSViewLevelLayout + 165
50  com.apple.AppKit                    0x00007fff895f883f -[NSSplitView layout] + 915
51  com.apple.AppKit                    0x00007fff895f81a4 -[NSView _layoutSubtreeWithOldSize:] + 373
52  com.apple.AppKit                    0x00007fff895f83f5 -[NSView _layoutSubtreeWithOldSize:] + 966
53  com.apple.AppKit                    0x00007fff895f83f5 -[NSView _layoutSubtreeWithOldSize:] + 966
54  com.apple.AppKit                    0x00007fff895f7e50 -[NSView layoutSubtreeIfNeeded] + 885
55  com.apple.AppKit                    0x00007fff895f79aa _NSViewLayoutSubtreesThatUseAutolayoutIfNeeded + 71
56  com.apple.AppKit                    0x00007fff895f7931 -[NSWindow _layoutViewTree] + 84
57  com.apple.AppKit                    0x00007fff89616e3d -[NSWindow layoutIfNeeded] + 246
58  com.apple.AppKit                    0x00007fff894bb63e _handleWindowNeedsDisplayOrLayoutOrUpdateConstraints + 612
59  com.apple.AppKit                    0x00007fff89bf1191 __83-[NSWindow _postWindowNeedsDisplayOrLayoutOrUpdateConstraintsUnlessPostingDisabled]_block_invoke1540 + 46
60  com.apple.CoreFoundation            0x00007fff8ed9c127 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
61  com.apple.CoreFoundation            0x00007fff8ed9c080 __CFRunLoopDoObservers + 368
62  com.apple.CoreFoundation            0x00007fff8ed8e188 __CFRunLoopRun + 872
63  com.apple.CoreFoundation            0x00007fff8ed8dbd8 CFRunLoopRunSpecific + 296
64  com.apple.HIToolbox                 0x00007fff8cb7956f RunCurrentEventLoopInMode + 235
65  com.apple.HIToolbox                 0x00007fff8cb791ee ReceiveNextEventCommon + 179
66  com.apple.HIToolbox                 0x00007fff8cb7912b _BlockUntilNextEventMatchingListInModeWithFilter + 71
67  com.apple.AppKit                    0x00007fff894b89bb _DPSNextEvent + 978
68  com.apple.AppKit                    0x00007fff894b7f68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
69  com.apple.AppKit                    0x00007fff894adbf3 -[NSApplication run] + 594
70  com.apple.AppKit                    0x00007fff8942a354 NSApplicationMain + 1832
71  libdyld.dylib                       0x00007fff867c35c9 start + 1

Thread 1:
0   libsystem_kernel.dylib              0x00007fff8d739232 kevent64 + 10
1   libdispatch.dylib                   0x00007fff924d9a6a _dispatch_mgr_init + 0

Thread 2:
0   libsystem_kernel.dylib              0x00007fff8d73894a __workq_kernreturn + 10
1   libsystem_pthread.dylib             0x00007fff83b6640d start_wqthread + 13

Thread 3:
0   coop.plausible.CrashReporter        0x000000010541c7dc -[DM_PLCrashReporter generateLiveReportWithThread:writer:error:] + 264
1   coop.plausible.CrashReporter        0x000000010541cb11 -[DM_PLCrashReporter generateExceptionReport:error:] + 208
2   coop.plausible.CrashReporter        0x000000010541b907 +[DM__PLCrashReporterStorage notifyCrashReportersWithHandledReport:] + 290
3   libdispatch.dylib                   0x00007fff924db323 _dispatch_call_block_and_release + 12
4   libdispatch.dylib                   0x00007fff924d6c13 _dispatch_client_callout + 8
5   libdispatch.dylib                   0x00007fff924d988f _dispatch_root_queue_drain + 935
6   libdispatch.dylib                   0x00007fff924e7fe4 _dispatch_worker_thread3 + 91
7   libsystem_pthread.dylib             0x00007fff83b68637 _pthread_wqthread + 729
8   libsystem_pthread.dylib             0x00007fff83b6640d start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib              0x00007fff8d73894a __workq_kernreturn + 10
1   libsystem_pthread.dylib             0x00007fff83b6640d start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib              0x00007fff8d7334de mach_msg_trap + 10
1   com.apple.CoreFoundation            0x00007fff8ed8eeb4 **CFRunLoopServiceMachPort + 212
2   com.apple.CoreFoundation            0x00007fff8ed8e37b __CFRunLoopRun + 1371
3   com.apple.CoreFoundation            0x00007fff8ed8dbd8 CFRunLoopRunSpecific + 296
4   com.apple.CFNetwork                 0x00007fff8f1bf220 +[NSURLConnection _resourceLoadLoop:] + 434
5   com.apple.Foundation                0x00007fff91b67dc2 __NSThread__main** + 1345
6   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
7   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
8   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 6:
0   libsystem_kernel.dylib              0x00007fff8d7334de mach_msg_trap + 10
1   com.apple.CoreFoundation            0x00007fff8ed8eeb4 __CFRunLoopServiceMachPort + 212
2   com.apple.CoreFoundation            0x00007fff8ed8e37b __CFRunLoopRun + 1371
3   com.apple.CoreFoundation            0x00007fff8ed8dbd8 CFRunLoopRunSpecific + 296
4   com.apple.AppKit                    0x00007fff8958066b _NSEventThread + 137
5   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 7:
0   libsystem_kernel.dylib              0x00007fff8d7383fa __select + 10
1   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
2   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
3   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 8:
0   libsystem_kernel.dylib              0x00007fff8d738136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff86f31c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff8f643544 _ZN3JSC14BlockAllocator22blockFreeingThreadMainEv + 228
3   com.apple.JavaScriptCore            0x00007fff8f638cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
4   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
5   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
6   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 9:
0   libsystem_kernel.dylib              0x00007fff8d738136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff86f31c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff8f643adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff8f643938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff8f638cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 10:
0   libsystem_kernel.dylib              0x00007fff8d738136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff86f31c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff8f643adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff8f643938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff8f638cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 11:
0   libsystem_kernel.dylib              0x00007fff8d738136 __psynch_cvwait + 10
1   libc++.1.dylib                      0x00007fff86f31c95 _ZNSt3__118condition_variable4waitERNS_11unique_lockINS_5mutexEEE + 47
2   com.apple.JavaScriptCore            0x00007fff8f643adb _ZN3JSC8GCThread16waitForNextPhaseEv + 171
3   com.apple.JavaScriptCore            0x00007fff8f643938 _ZN3JSC8GCThread12gcThreadMainEv + 88
4   com.apple.JavaScriptCore            0x00007fff8f638cff _ZN3WTFL19wtfThreadEntryPointEPv + 15
5   libsystem_pthread.dylib             0x00007fff83b68268 _pthread_body + 131
6   libsystem_pthread.dylib             0x00007fff83b681e5 _pthread_body + 0
7   libsystem_pthread.dylib             0x00007fff83b6641d thread_start + 13

Thread 12:
0   libsystem_kernel.dylib              0x00007fff8d73894a __workq_kernreturn + 10
1   libsystem_pthread.dylib             0x00007fff83b6640d start_wqthread + 13

Thread 13:
0   ???                                 0x0000000000000000 0x0 + 0
