### ISSUE TITLE
Open info sidebar closes after switching from pages mode to configure mode and back

### ISSUE THREAD

**Issue by leifottosson** [yourhead/s3#353]
Working in pages mode with open info sidebar.
Switches to configure mode and back to pages mode.
Info sidebar is closed.

**Comment by yourhead** [comment]
can you describe what you mean by "pages mode" and "configure mode" which buttons, specifically do you click to do this?

**Comment by leifottosson** [comment]
These buttons:
![working-mode](https://cloud.githubusercontent.com/assets/5895269/8916372/4b3e3520-34ab-11e5-80fc-806b86b31c98.jpg)

**Comment by leifottosson** [comment]
These buttons:
![working-mode](https://cloud.githubusercontent.com/assets/5895269/8916392/709b960a-34ab-11e5-8405-a5c65c04edda.jpg)

**Comment by yourhead** [comment]
i'm afraid i cannot make this happen. i've tried a number of things.

is there anything you think i might need to do to see this myself?

does this happen every time for you or just something that happened one time?

**Comment by leifottosson** [comment]
Happens every time for me. Launch RW. Create new project. Add stacks page and info sidebar is open. Switch to config and back to page and info sidebar is closed.

**Comment by yourhead** [comment]
Ah...   i just read this wrong, i was thinking "library sidebar" not "info sidebar".

Unfortunately the info sidebar is owned by RapidWeaver. When RapidWeaver decides the info bar should be closed Stacks has no power over that.

In this case RapidWeaver closes this sidebar when you enter into config view (i guess because config view sometimes has its own sidebar).  I can't change that behavior.  Sorry.

**Comment by leifottosson** [comment]
Then it's not a bug. That's a good thing! :-)
