### ISSUE TITLE
Would be nice to have %childCount% for parent

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#391]
It would be nice to be able to get access to the count of children in the parent stack. This would allow for some flexibility in Edit Mode.

**Comment by joeworkman** [comment]
The following 2 macros would be nice to have... 

%childIndex% - This is basically %repeatIndex% but for childOf stacks
%childCount% - The number of children added

**Comment by yourhead** [comment]
studied. but i'm going to give this one the nix. this would imply that we'd have to cache-flush children whenever items were added/removed from the parents. that would cause a large hit to performance for a feature that seems to have pretty limited applications -- and a not-too-tough workaround with JS.

**Comment by joeworkman** [comment]
Its not hard with JS. But it is with PHP. I have a couple of stacks that still use the `%[repeat]%` API because I rely on the %repeatIndex%.

**Comment by yourhead** [comment]
First about childCount

this isn't really feasible as far as i can see. a stack can have multiple containers -- each will have a different number of children.

that said, you can customize containers. that's exactly what addTypes, addInit, and maxChildren are doing. so i think there are two possible ways forward:

1. if we need to box the user in while they're in edit mode, we should add more things like addTypes/addInit/maxChildren.  maybe minChildren? i dunno -- if you can think of other stuff maybe i can find a way to add it.
2. if your use-case needs to do some calculation based on the number of items inside -- then do that using JS.


Now about %repeatIndex% -- this is actually a variable would need to be passed from the parent to the child -- and then it would affect the child's template replacement.

as i mentioned above -- this means flushing the cache far more often because this might be the case. this is (a piece of) exactly what we replaced `repeat` to avoid:  unnecessary cache flushes and re-renders of all of the repeating content.


i have ideas for how to accomplish more general purpose dynamic language things (like loops and such) but they require that templates be "compiled" to make detecting precisely when re-renders really need to take place. i can talk more about distant plans privately.

but within stacks as it is today i don't think this will be possible. going to have to stay in JS land for now.
