### ISSUE TITLE
Add a group stack

### ISSUE THREAD

**Issue by ghost** [yourhead/s3#400]
Add a very basic stack that would enable a user to group stacks for easier setting out of pages.
'Maybe' the ability to name the group similar to Partials but with the word 'Group' preceding the name.
As I understand it from Tav such a stack can be div-less and thus leave no footprint when published.

**Comment by yourhead** [comment]
this would essentially be a one-column stack with no exported div. correct?

some of stacks now contains features that are specifically designed for pro-users and users with understanding of things like "divs" -- but no all areas.  after some missteps in the past, i now aim to have the built-in stacks be understandable by the least techy -- and let the other areas be filled by the 3rd party stacks.

since the only distinction between a "group" and "one column" would be the exported div i think this would be very confusing to the non techy -- so i'm going to have to leave this one for 3rd party devs.
