### ISSUE TITLE
searching does not seem to pick up group, sometimes finds odd results

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#42]
I'm seeing a couple of issues that appear to be related to the group key:
- Although specified in the Info.plist file, stacks are not sorted by the group key, but instead listed as "Unknown"
- When selecting an "Unknown" stack, such as Armadillo, "NimbleHost" is displayed as a tag in the Details pane, and clicking on that "NimbleHost" tag will display all "NimbleHost" stacks. Yet searching for "NimbleHost" returns no results. (For reference, "NimbleHost" is only specified as a group key, and as a RWAddonAuthor key in the plist file.)
- Searching for a term specified in the group key of a stack's plist file (but not anywhere else) does not display that stack in search results. I would expect the search functionality to include the group key when searching.

Let me know if you need further details or a stack to test with.

**Comment by yourhead** [comment]
i think you're mixing up a few interesting behavior here -- you should probably try to isolate out just one thing, be very specific and file that as a bug.

**Comment by NimbleHost** [comment]
Roger that.

**Comment by yourhead** [comment]
- the group key is deprecated.  you should use tags now.  see this for more info:  https://github.com/yourhead/s3/wiki/Tags-and-Groups
- things start up in a weird state. it's initially set to "author" sorting -- and not many stacks are using that currently.  it's filed in this bug:  https://github.com/yourhead/s3/issues/33
- the searching does seem wonky to me too. i think that's a real bug

**Comment by yourhead** [comment]
I suspect the real bug here is that the search is being overly literal and should ignore whitespace, capitals, etc.

**Comment by NimbleHost** [comment]
Was thinking about the possibility of customers with non-updated stacks, or devs who are slow to implement tags, and what customers would expect to happen in that type of situation.

I should've isolated this and been more specific though. 😳

**Comment by yourhead** [comment]
So, as that other web page says...  it does try.  The idea is that it will use tags if tags are available.  If there are no tags in the plist then it falls back to the group.  And the group becomes the one and only tag.  And searching **_should**_ pick that up.  (but i think the search not working quite right -- it really is a bug -- there's something strange).

The one oddball caveat is that a bunch of devs have added something odd to their tags (since they had no purpose prior to this week) -- in that case things get nutty.

Also:  the default sorting order will be by tags in the future, you can click on the little gear and choose Arrange Stack > By Tag to see what's probably a bit more expected.

**Comment by NimbleHost** [comment]
Thanks for the info - I'll do my homework first, the next time I run into something. In my haste to "contribute" I was a bit too quick on the trigger.

**Comment by yourhead** [comment]
s'aright. i'm happy to have too much reporting. ;-)

**Comment by yourhead** [comment]
I think this bug is probably fully covered by these two more specific bugs:
https://github.com/yourhead/s3/issues/45
https://github.com/yourhead/s3/issues/46

I'm going to close this for now. If group info still doesn't seem to be making it through in the next build, let me know and we'll reopen this one.
