### ISSUE TITLE
Various issues with checkbox arrays

### ISSUE THREAD

**Issue by designdisorder** [yourhead/s3#424]
I have an weird issue with checkbox controls which show an inconsistent behavior in terms of how render into code, the default values and the actual front-end behavior.
1. Using an array of checkboxes in my example (>= 2) you click on the first checkbox and all other checkboxes in that array switch state at the same time. You can still individually click on the 2nd, 3rd, etc. and set them individually, but somehow the first one is linked to the others. I checked your example stack and it doesn’t show the issue
2. The checkboxes don’t respect the default settings
3. When generating code the trueValue and falseValue defined for those checkbox arrays are not used. They just render as True and False. I am using the following definition, which strangely enough works for other checkboxes, like the Radio setting in that example further down
   
   ```
       <key>trueValue</key>
       <string>&lt;true/&gt;</string>
       <key>falseValue</key>
       <string>&lt;false/&gt;</string>
   ```

I will send you the example to your mac.com mailbox

**Comment by yourhead** [comment]
this problem arrises from your interesting use of custom IDs.

you have assigned many items to the same ID.  and while this is a generally OK thing to do when the two controls are the same type -- it has undefined behavior when the two controls have different types.

in this case you're assigning the ID called "default" to both a single checkbox and a checkbox array.  the single checkbox has a single value output.  the arrayed control has an array of outputs.

in order to be more tolerant of changing stacks that might want to change from single to arrayed control or vice versa stacks is tolerant to the wrong type of value and attempts to do something appropriate with it.  in this case if you assign a single boolean true value to an array -- the control sets all checkboxes to true.

a good use case for this is if a stack went from having a single "border enable" to checkbox to having an array of controls for top/left/bottom/right border enable. of the possible ways to interpret the value:
- assign true to none of the array index
- assign true to a single array index
- assign true to all the array indices.

the last one seems like the obvious choice to me.

i'm completely open to other ways to try to build the thing that you're working on here -- but i don't see an easy way to accommodate this specific request.  that is...  be able to assign the same ID to both a single and arrayed checkbox control.

**Comment by designdisorder** [comment]
That's it. I was running into this with other custom items and pretty much came to the same conclusion, but in this case it was not so obvious. 

With that in mind I think the behavior you implemented is as good as any of the other options. I just have to change the ID to fix that.

Do you think the other issues I am seeing there are caused by that as well? Anyway, i will find out after I changed the IDs :) Thx

**Comment by yourhead** [comment]
I believe the other oddities are related too.

At the implementation level the value of a single-items is a Boolean. And the value of an array type is an Array. The default values try to set/modify these values. If one control sets the value to an array and the other control sets it too a Boolean as the default something has to give.  You cannot have a variable set to two different values. It will always resolve to one value eventually.
