### ISSUE TITLE
Partial options not synching

### ISSUE THREAD

**Issue by claudemangen** [yourhead/s3#449]
When I change the margin, padding or "Hide this Stack" in one partial, these options are not synchronised with the other partials. Only the stacks inside the partial are synchronised, but not the options of the partial itself.

**Comment by yourhead** [comment]
Amazing that this has slipped through the cracks. Thanks for catching it.

**Comment by yourhead** [comment]
When I first read about this bug I thought it was referring to a different thing, I'm afraid.  I thought this was referring to the properties inside the partial itself -- but those do seem to work fine.

I think what you're referring to are the properties on a particular instance of a partial.  These are supposed to be unique to that instance.  This is important so that this particular partial can be used in a variety of different places that might require slightly different external properties.

If I've misunderstood please let me know and we can reopen. Thanks.

**Comment by claudemangen** [comment]
Hi, yes, now I understand your decision, why it works like this. Thanks. Nice weekend to you.
