### ISSUE TITLE
Rapidweaver crashes deletes all previously saved Partials

### ISSUE THREAD

**Issue by alxalxnet** [yourhead/s3#461]
I'm waiting for a crash to happen again so that I can get the console log and provide more info. 
Meanwhile, I'm trying to recover the Partials from a backup but I can't find where they're saved. Does anybody where they're stored?

**Comment by yourhead** [comment]
partials are part of the document, they are not independent things. they cannot be "deleted" nor do they exist somewhere independent on your drive.

it sounds to me like you crashed before saving or that perhaps the crash corrupted the document.  if you send me the corrupted document in question, i can give you more info.

however, bug reports need to be both testable and actionable. since i cannot test for this report to check if i've fixed the bug, nor do anything about this behavior, i have to mark this bug as closed.

if there is more detail that could make this bug testable and actionable, then we can reopen and fix it.
