### ISSUE TITLE
Update Window doesnt always show last stacks in list as Installed

### ISSUE THREAD

**Issue by ghost** [yourhead/s3#471]
Sometimes when there are a few updates the last stacks to be updated doesn't move down into the list of 'Installed' stacks. The update completes but the window remains at 'Installing'

![screen shot 2015-08-24 at 13 03 07](https://cloud.githubusercontent.com/assets/13369615/9439701/3c2e13e0-4a61-11e5-9bae-b784580dacf3.png)

**Comment by yourhead** [comment]
When there is a problem with the update, with the update server, with the downloaded data, etc.   then this is the expected behavior.

In cases like this there may be error data that is provided in the console to show what the cause of the failure was.  However it's also intentional that failures are quiet -- because when contacting hundreds of websites and downloading lots of data there the liklihood of encountering some problems is very high.
