### ISSUE TITLE
Edit Mode garbled when editing settings while in preview mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#482]
This may only be with Child stacks? I put Gyro2 on our DB share so that you can test this out.

Basically if you change any of the settings while in Preview, when you go back into Edit Mode, you only see the %slice% as text. If you change a settings while in edit mode, it fixes itself. 

https://www.dropbox.com/s/0a3eizuom05wyn1/gyro2.mov?dl=0

**Comment by joeworkman** [comment]
Yes... garbled is a highly technical term...

**Comment by yourhead** [comment]
does this stack use a repeat?

**Comment by yourhead** [comment]
notes:
- intermittent
- %slice% not repopulated when refresh is triggered from edit mode
- the Gyro stack seems to be particularly susceptible to the behavior
- does not involve %repeat%
- does not involve %add-types%
- slice remains as the original template instead of being replaced by meta templates

**Comment by yourhead** [comment]
this is the regex mutable string bug. hopefully this should be long cured. i suspect this one just forgot to get marked as fixed.

**Comment by yourhead** [comment]
we can re-open if the symptoms occur again.
