### ISSUE TITLE
Feature Request - add captions to images

### ISSUE THREAD

**Issue by girlcarew** [yourhead/s3#497]
It would be good if you could add captions to images in the 'Images' stack and the 'Float' stack.

**Comment by joeworkman** [comment]
Put a text stack below the image?

**Comment by yourhead** [comment]
One way to read this is that the request is for an image stack with a caption.  This can't happen because we can't really modify the basic stacks that are used as building blocks everywhere else without breaking tons of things.

Another way to read this is that we should have a stack that has both an image and a caption together. But this would subvert the concept of stacks -- that you can build things like that yourself, create partials out of them if you need many.

If building something from the basic components is something a novice user can do, then there probably shouldn't be a stack that does that -- we should just let users do it themselves.
