### ISSUE TITLE
Directional arrows to resize info sidebar popover do not appear until popover has been moved

### ISSUE THREAD

**Issue by NimbleHost** [yourhead/s3#50]
This may be the intended behavior, in which case feel free to ignore and close this issue.

In short, since the popover can be resized, I would expect to see directional arrows (in place of the mouse cursor) when the mouse is hovered over the edge of the popover window. These directional arrows do appear "as expected" after the popover is moved to a different location from its initial placement, but not otherwise.

**Comment by yourhead** [comment]
i would expect it too -- however it is not an option in Mac OS X as far as i can tell.
popovers can change size -- just not with the standard window resize controls -- at least not as far as i can tell.

that said, i think a reasonable feature request instead of this is that the size of the popover is at least maximized to the size of the content and the screen it's on.
