### ISSUE TITLE
Partial Content not refreshing after changing pages within preview mode

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#503]
I totally figured out the steps to replicate the partials bug where the partial content disappears

Project File: https://infinit.io/_/35PCDn4
1. Open that project file (requires Foundation)
2. Preview the Home page
3. While in preview switch to the About page
4. Switch to Edit Mode for the About page.

The `Header` partial has no content until to double click it to edit it and back out

**Comment by joeworkman** [comment]
I am getting a lot of tickets about this. Is there anything that I can do to help.

**Comment by joeworkman** [comment]
This is still throwing people off...

**Comment by yourhead** [comment]
the challenge here is in isolating the problem. foundation has lots of moving parts.
as always, if problems are isolated in a way that makes them obvious, i'll fix them immediately.
when things are complex they get put off.
sorry.

**Comment by yourhead** [comment]
debugging notes:

partial export is non-reentrant due for two reasons:  loop detection and node-control swapping during the push-in to edit mode.
- during loop detection the encapsulated flag is set when export begins.  this is used to detect a loop.  when the loop is flag is already set we break the loop and return.  to make export reentrant we must detect the loop combinatorially rather than sequentially.
- when a partial is edited the top-level node controller from the currently ui is swapped out with the partial's private node controller.  to make export reentrant we must pass a reference to the exporting node-controller rather than using the current node controller.

when the page is changed from within preview two different exports (one edit and one preview -- and of different pages) are triggered on different threads. depending on the length of the export and where the partial export is within the each, the partial export calls can overlap in time. when the exports overlap their state (node controller and encapsulated flag) are accidentally shared.

there are two possible solutions to this problem:
1.  ensure sequential export by calling all partial exports on a single sequential thread.  
2.  remove the two bits of state that currently exist.

**Comment by yourhead** [comment]
first attempt:  fail
- pass in node controller to the export methods.  this has proven to be very difficult.  some of the base-class (YHNode) methods rely on the existence of a node controller property during export. each of these methods needs to be found and overridden to use the passes node controller instead.  this is very complex and certainly prone to error.

**Comment by yourhead** [comment]
second attempt: fail
- create a sequential export queue and move all export methods to that queue.
  it is not clear how, but this immediately causes deadlock. i suspect this has to do with RW blocking the main thread during some exports.  this means that if any part of the sequential export queue calls out to the main-thread the export queue waits forever. i suspect this would normally be mitigated by completing other exports which unlocks RW's lock.  whatever the case, i think this is a dead end.

**Comment by joeworkman** [comment]
Lesson learned about using file sharing services to post files in an issue... the URL to the project file that I created no longer works. Sorry. 😐

**Comment by yourhead** [comment]
s'alright. i know what this problem is -- but i'm basically at an architectural dead end. this one requires a deeper level re-build of some parts of partials. it's not going to happen in the near term.

**Comment by joeworkman** [comment]
Anything that we can do to prevent nested partials for now then?

**Comment by yourhead** [comment]
i'm going to take this back. i'm not sure this bug exists any more either. i suspect the change that i implemented to update for page-scoped-properties (which adds a sequential queue just for edit mode -- a solution i was trying for above).

in any case, i had my own set of test-case files for this and none of those produce any sort of error.

**Comment by yourhead** [comment]
i this bug is now gone in the recent beta
