### ISSUE TITLE
min/max key not (always) obeyed in number-2/number-4 arrays

### ISSUE THREAD

**Issue by marathia** [yourhead/s3#518]
When setting a `min` and/or `max` key to `number-2` or `number-4` arrays, those values are only obeyed when using the up/down arrows; not when typing a value in the input field.

**Comment by yourhead** [comment]
this is a long-standing behavior of stacks -- that min/max do not apply to the manually entered values.  i don't think we can change it at this time because there could be stacks that rely on this behavior.

we might be able to add a switch to imply hard limits on the text-entry too -- but i'm not sure that i really like that, to be honest.

i don't like manual text entries that "validate" -- it tends to create frustrating UX.

**Comment by marathia** [comment]
I understand what you're saying, but please be aware that the `min` and `max` values are obeyed in a single `number` array, which can be confusing.

**Comment by yourhead** [comment]
alright. that changes everything. just ignore my blathering from before.  ;-)
you got me. mia culpa. i'll fix it.
