### ISSUE TITLE
Changes to file templates not reflected in preview

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#541]
If I change a setting that controls the content of an each scoped file template, those changes do not take place until RapidWeaver is restarted. 

I would expect the changes that were made in the settings would automatically get modified just like HTML does.

**Comment by yourhead** [comment]
this is a bug, but one that should be encountered only by developers and only very rarely when they are first modifying the template plist keys.  after that this bug fix would have no benefits.

however the cost is that that it would require cache-testing some of the most time critical bits of stacks.

for now, i'm going to say the cost of fixing this bug outweighs the benefits and leave it as is.

if there is a way to achieve this that doesn't come at so steep a cost or if the bug is determined to be worse than i currently understand it, then i'll reopen.
