### ISSUE TITLE
Directory Assets of Stack A overwrite Directory Assets of Stack B

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#547]
I have 2 stacks with following `assets` configuration in order to take all files inside the sub directory `assets`. The file names in the different assets directories are of course different:

```
    <key>assets</key>
    <array>
        <dict>
            <key>fileName</key>
            <string>assets</string>
            <key>siteAsset</key>
            <false/>
        </dict>
    </array>
```

In preview and publish, the whole folder content of `/files/assets` will be **replaced** by the last exported stack instead of a **file merge**. The

**Comment by joeworkman** [comment]
This has been the same behavior since Stacks 1. Name your assets wisely.

**Comment by yourhead** [comment]
this is the expected behavior. i don't think there is any other feasible behavior. doing a file-merge would require renaming files which would likely break many scripts.

since no matter what i do some scripts will need to be rewritten in order to work within stacks, i think it's best if i do the simplest and most easily understood thing where the limitations are obvious -- rather than something that's complex with difficult to find limitations.
