### ISSUE TITLE
Float ellipsis in number-4

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#559]
It would be nice if the ellipsis added in a number-4 could be tweaked so that it does not happen unless you have 4 digits. 

Have a look at the following images. 50.0 gets an ellipsis when it should be able to fit. It does fit when you go to edit the number. 

![screen shot 2016-04-07 at 11 44 10 am](https://cloud.githubusercontent.com/assets/225628/14362909/8d7b1326-fcb6-11e5-9f82-436ee73d63c5.jpg)

![screen shot 2016-04-07 at 11 44 16 am](https://cloud.githubusercontent.com/assets/225628/14362912/911e8c92-fcb6-11e5-89d7-93a986bb86a2.jpg)

**Comment by yourhead** [comment]
this seems to happen because each of the controls is stretchable horizontally to fit the 3 different variants of info-panel width:  RW6 sidebar, RW7 sidebar, and RW7 window.  depending on the particular variant of the sidebar the four controls can have different widths by 1px -- and apparently that's all that's required here.

i've triple checked. all of the views have the same initial-width, the same constraints, and everything seems to be working as expected -- they just have slightly different widths in their various containers.  :-/

IOW:  i don't think there's anything i can do about this one. sorry.
