### ISSUE TITLE
Text stack - Align contents right adds space at top, regardless of view mode

### ISSUE THREAD

**Issue by halsteadb** [yourhead/s3#562]
RW6 & 7
Standard text stacks inside a standard 2 column stack (1 text stack in each column)

Left column - align right
Right column - align left

Left column gets a bit of padding or a line added in any edit view mode as per the image.

Expected behaviour is that they align properly in all edit modes.

![2col-txt-ralign](https://cloud.githubusercontent.com/assets/16257873/14395562/6aa55696-fda0-11e5-8654-9cfeab7897f3.jpg)

In preview and published site, everything aligned correctly. This is strictly an edit mode issue.

**Comment by yourhead** [comment]
Yep.

But you'll also find the same behavior in the RapidWeaver Text page. And the Blog page. And every other page too.  ;-)

That means this bug is in the RW Styled Text engine.  You can file it if you like, but I'd advise not wasting your breath -- this bug has existed since before my time in RapidWeaver (before 2005) -- and I file it regularly. The likelihood of it changing any time soon is very small.

I've included a snapshot of two Text pages (no stacks involvement at all) they show the same behavior in the default Alpha theme.

![Text Page](https://dl.dropboxusercontent.com/u/433436/Pasted_Image_4_8_16__2_49_PM.png)

**Comment by halsteadb** [comment]
Ahhh, roger that sir. (closed)

Brad

**Comment by yourhead** [comment]
On second thought. File it with RW. They have some new hot-shot devs nowadays. And seem to have "the fire in their belly" these days.  You never know.  This could be the release that fixes it!
