### ISSUE TITLE
Icon Picker Control (feature request)

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#588]
Perhaps for S4.

A new custom control to allow the user to pick a Font Awesome icon, in a more graphical way.
I envisage this control being a custom view to match the image control. When clicked it will reveal a small scrollable custom view, either popover, or modal, that will have all the icons on display. The user clicks an icon, and it is displayed in the controls custom view (well).

Font Awesome would be a nice start, but could be extended to include other icon libraries in the future.

Now for what does the control output as a value:
It could just output the Font Awesome HTML. 
or it Could output an SVG generated from the glyph. (that would be nice!)
Either way, I think this would be a nice step forward, as we all want to and do in many stacks already offer the user some way of picking an icon, but it's currently a bit non-intuitive to users that don't know anything about Font Awesome codes if we ask them to enter one, or a bit messy and slow if we try and build in huge plist files with a gazzilion icon options in select controls.

**Comment by yourhead** [comment]
Hmmm...

It does seem like it would improve the user experience, however building an entire custom control class just to support a single use case makes me very wary.

Whenever problems need to be solved we should always look for existing solutions instead of inventing new UI. If there is no reasonable solution to the problem you must first ask yourself why no existing UI solves this problem. In the vast majority of cases it means that you're solving the wrong problem.

Furthermore, building a custom UI to solve a problem with only a single use-case is another warning sign that something is clearly wrong.

I think we should consider the broader problems we're trying to solve with this and see if there are any other ways to skin this cat. Even though none have come to me yet, I suspect there are other ways to improve this experience.

**Comment by yourhead** [comment]
i'm going to put this one to bed. i think the complexity and maintenance of this would be a nightmare. not worth the cost.
