### ISSUE TITLE
When detailed settings are disabled the conversion back to single setting is imperfect

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#598]
This works with any stack but using a text stack for this example. 
1. Add a Text stack to the page. 
2. Click on the + button for detailed margins. 
3. Set the top margin to 60px. 
4. Click on the - button to turn off detailed settings. 

You will now notice that the stack has 60px on all side of the stack. It should be 0px.

**Comment by yourhead** [comment]
The current behavior has been around since Stacks 1.  The idea is that the maximum value of the detailed settings is used to create a new single setting.

The recently introduced bug is that the single setting in the info sidebar doesn't update with the newly calculated maximum setting.  The stack does actually behave this way -- but the control still shows the previous setting.

**Comment by yourhead** [comment]
There's a user-experience caveat here too:  When this behavior was added to stacks back in stacks 1 it was because there were very few customizable settings in any stacks.

Now, many developer have stacks that have detailed/simple settings -- but there is no api to add this sort of complex binding between those two modes.

It might be easier to understand and definitely would be more orthogonal to make these all behave with the simple behavior:  no binding between the detailed/simple modes.

**Comment by yourhead** [comment]
I'm not sure what the end solution should be here -- but I'd like to resolve this one way or another before 3.5.0

**Comment by joeworkman** [comment]
If I disable the detailed padding, I would expect that the value of the simple slider be 0 or whatever value it was previously set to.

**Comment by yourhead** [comment]
Hmmm...    yeah...    that's just not how it has ever worked in Stacks. And...   well...  I've spent a lot of time making it work NOT that way.

I can see you point. But I think I just disagree. I kind of like how it works right now. And, well, it's worked that way for a long time.

If this was a huge support issue, or there were some clear HIG idiom that was being violated, I'd be willing to change -- but this seems like it's just down to designer/architect preference of how best to interpret the user's intent. This is how I'm choosing to do it. Sorry.

**Comment by joeworkman** [comment]
No skin off my back. There are much bigger fish to fry than this one... :-)
