### ISSUE TITLE
Max number of children for %slice%

### ISSUE THREAD

**Issue by barchard** [yourhead/s3#602]
It would be nice to be able to set the max number of children that a user can add to a Slice instance. Eg.

`%slice -addTypes="com.whatever" -addInit=0 -max=5%`

**Comment by joeworkman** [comment]
Dup #160
Dup #390

**Comment by yourhead** [comment]
i think there are really several separate requests being made  --  but they're kind of muddled together and unspecific so it's hard to tell.  so let me try to clarify and preen these a bit
1. the maximum number of children that can be added.  (#602 & #390)
2. the maximum number of instances of a specific stack on a page.  (#160)
3. the maximum number of instances of a specific stack in a parent.

#602 (this bug) is clearly a dupe. so i'll mark it as such.
#160 needs to be modified because it's infeasible -- so i'm going to rewrite it so it's like #3 instead.
