### ISSUE TITLE
Position Select behind Number in Stacks Settings

### ISSUE THREAD

**Issue by DeFliGra** [yourhead/s3#633]
Pure selfish but probably difficult wish. 

I have some stacks where I allow user to choose the unit for their number input. Could be width, height, margin, padding – where user are allowed to enter unit = px, %, vw, vh etc.

Would be quite nice being able to position the unit behind the number... would same some settings height space.

**Comment by yourhead** [comment]
could you describe in detail more of what you mean?

i see what you're trying to do, but i do not understand quite what you "position the unit behind the number" -- what do you mean by "behind" -- do you mean "to the left of" -- if so, aren't the units already to the left of the number?

if you mean "underneath" then i just don't understand.

**Comment by DeFliGra** [comment]
On the same line: number + select (choose between px, %, vw, em etc.)

User could type the number and then – on the same line – select the unit.
Instead of now type number, go to next field below and choose the select box with the units.

NUMBER + SELECT

instead of

NUMBER
SELECT

**Comment by yourhead** [comment]
Unfortunately it's not possible to do architecturally today -- this would means driving two values of different type (the number + the unit selection) with the same control.  Right now all controls drive a single value -- or an array of like-values.

I can put this in the "someday" category, but I wanted to let you know that this probably won't happen in the near-term because it would be quite a significant change.

**Comment by yourhead** [comment]
infeasible without significant change
