### ISSUE TITLE
Feature Request: Include vuejs as additional inbuilt library

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#653]
Beside jQuery, font awesome etc. maybe it is possible to include also https://vuejs.org as one of the inbuilt standard libraries.

**Comment by yourhead** [comment]
I think this is a good idea.

Although I'm a tad worried about interoperability.  jQuery's "no conflict" mode was the one major win thet allowed us to interoperate no matter what themes and users were doing.

**Comment by jrondorf** [comment]
True. Maybe this helps:
https://github.com/vuejs/vue/issues/2349

**Comment by yourhead** [comment]
does that work? or is it just a proposal?

**Comment by jrondorf** [comment]
In general, every Stack would get it's own Vue instance (or creates it for itself):

`var vm = new Vue({
  el: '%id%',
  data: data
})`

With this, more than one Vue instances are able to live in peace together on the same page.

It is even possible to register components locally: https://vuejs.org/v2/guide/components.html#Local-Registration

But we should only allow to use the latest / one version of Vue and not different versions (e.g. 1.0.27 and 2.0.4 on the same page -> only latest 2.0.4 / no version choice at all).

**Comment by yourhead** [comment]
that will only work if if Vue was specifically designed to do that.  if they use **any** global state, or add **any** global functions then it will not work as other versions that the user or theme has loaded will collide.

that's probably OK...   for now...    since vue is still pretty rare.
but if the stacks-library-include is useful it's because Vue is becoming more popular. so the more useful the library function the more likely it is cause problems.  that's an unhappy situation.

**Comment by jrondorf** [comment]
Will try to get some answers: https://forum.vuejs.org/t/does-vue-2-store-anything-globally-use-vue-in-no-conflict-mode/2680

**Comment by yourhead** [comment]
me too.

but i'm fighting bigger fires on the RW7.1 front at the moment -- so you'll excuse me if i put this off for a bit.  😉

**Comment by jrondorf** [comment]
More than fine ;-) Good luck!

**Comment by yourhead** [comment]
in beta 2

**Comment by jrondorf** [comment]
Woa! Your great! What will be the library name to use?

**Comment by yourhead** [comment]
you can use "Vue" or "VueJS" -- i'll publish more details soon.
