### ISSUE TITLE
Update to FA 4.7

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#663]
Users have been asking for them... 47 new icons
http://fontawesome.io/icons/

**Comment by elixirgraphics** [comment]
Loading Font Awesome from the CDN loads v4.3 instead of 4.7: 

![screen shot 2017-05-03 at 11 44 40 am](https://cloud.githubusercontent.com/assets/2013801/25669436/890ec1d2-2ff7-11e7-8b12-98a15c0a5917.png)

If loaded locally 4.7 is loaded:

![screen shot 2017-05-03 at 11 44 48 am](https://cloud.githubusercontent.com/assets/2013801/25669442/8d449a74-2ff7-11e7-9e81-c235055e7f32.png)
