### ISSUE TITLE
%%[[if edit]]%% wrong after previewing and switching back (3.5b12)

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#716]
I have a RW document with 2 pages. That's important, because the issue does not occur with 1 page.

A stack with new %%[[if edit]]%% macros will not get the mode correctly, if switching between the pages, and also the preview modes. So, selecting page 1, afterwards page 2, switching to preview for page 2, selecting page 1 (directly previewed), and switching back to edit, will lead to an incorrect mode.

See attached demo document and stack for reproducing the issue.

[Archive.zip](https://github.com/yourhead/s3/files/1133383/Archive.zip)

**Comment by yourhead** [comment]
The info above is helpful, but not nearly sufficient for me to find and fix the bug. What I need:

1. What I need to do to make the bug happen
- it's best if you can tell me how to create a brand new document -- rather than providing a document
- it's best if this has the absolute minimum number of steps/details -- if a Text stack will make it happen don't use your stack -- if one stack will make it happen, don't use two.

2. What I should look for when the bug happens
- in your above description you tell me that "macros will not get the mode correctly" -- which one should I be looking for -- where on the page will it be

3. Tell me:
- what you expected to happen
- what will actually happen

**Comment by jrondorf** [comment]
1. 

- Create a RW document with 2 stacks pages.
- Drop example stack to the pages.
- The stack just contains following html template. But actually I experienced the bug with a lot more complex stack, so I reduced it to the minimum already.
```
%%[[if edit]]%%

Display in edit mode

%%[[endif]]%%

%%[[if !edit]]%%

Do not display in edit mode

%%[[endif]]%%
```

2. 

- see above

3. 

- the !edit part will be displayed in edit mode, see video


[2017-07-09_23-21-28.mp4.zip](https://github.com/yourhead/s3/files/1134088/2017-07-09_23-21-28.mp4.zip)

**Comment by jrondorf** [comment]
The error occurs at 35 sec. mark

**Comment by yourhead** [comment]
awesome. perfect. thanks so much!

**Comment by yourhead** [comment]
ooof. this is a bad bug. can't fix this one in one day. will have to spend a bit on it.

i may release beta 13 before this one is done -- but this will be my top priority going forward.

**Comment by yourhead** [comment]
fixed in beta 13
