### ISSUE TITLE
Stacks with no HTML templates

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#754]
If you have a stack with no HTML templates, a `%slice%` is added into Edit Mode. 

Workaround is adding a blank template file.

**Comment by joeworkman** [comment]
[NoHTML.devstack.zip](https://github.com/yourhead/s3/files/1243006/NoHTML.devstack.zip)

sample stack

**Comment by yourhead** [comment]
what's the use case for a stack with no HTML? what should show up in edit mode in that case?

**Comment by yourhead** [comment]
closing this since the question went unanswered. there still doesn't seem to be a valid use case for changing this as far as i'm concerned.

whatever the reason for using a stack without a template -- i suspect it will be easier to fix that than to change this behavior since this is a deep part of Stacks 1.0
