### ISSUE TITLE
Server key over HTTPS

### ISSUE THREAD

**Issue by barchard** [yourhead/s3#760]
May be a good idea to serve this file over HTTPS instead of HTTP?

https://github.com/yourhead/s3/blob/41052bbb696038dfa60686162b11267ac237d615/secure_stack_API/YHStacksUpdate.php#L22

**Comment by yourhead** [comment]
all the files are served from github, which of course supports https. do you mean something else?

**Comment by barchard** [comment]
yes, but this `.pem` file is *not* being served via HTTPS:

```
const STACKS_PUBLIC_KEY_URL = "http://yourhead.com/appcast/RW6/Stacks3/stack_public_key.pem";
```

**Comment by joeworkman** [comment]
This is what pull requests are for...

**Comment by barchard** [comment]
changing the URL doesn't mean he has a cert ready to make this work :)

**Comment by yourhead** [comment]
if you're concerned about the pem file being spoofed (like, seriously dude? how much trouble do you think someone is going to go to in order to steal a stack -- why are even wasting our breath here????) then you can download the pem from GitHub via https   https://raw.githubusercontent.com/yourhead/s3/master/secure_stack_API/stack_public_key.pem

and server that yourself from your own cert.



but, frankly, i wouldn't bother -- we are not wikileaks -- and the CIA is not trying to avoid spending $25 on your stack.

this is indie software -- we don't have to be perfect to the n-th degree -- in fact we ****MUST**** NOT BE PERFECT -- because in following every rule and crossing every t and dotting every i we will surely lose out to the bigger guys that can afford to do that. 

we ****MUST**** cut some corners in order to stay competitive and keep our companies alive. deciding which corners to cut is the difficult part. cut the wrong corners and we're toast. focus on the wrong details and we're done.



the original version of the php linked to the https GitHub version -- but GitHub will only serve it a few dozen times and then raises a flag and kills off the link.  

instead of waisting time and effort building a certified server in order to host this single file -- i chose to cut a corner -- i chose to put in the non-https link and let users handle it themselves. not because i think that's a good thing -- but because it think it's a good-enough thing.

SOMETIMES THE RIGHT THING TO DO -- IS TO DO THE THING NOT RIGHT

if you feel strongly that serving the file yourself is opening a security hole that can be practically exploited by hackers trying to steal $25 of stuff -- then please make your case, i'll listen.  until then, i have more pressing bugs to fix.

**Comment by yourhead** [comment]
it's the right thing to do. but is low on the practicality scale. i'll put it on the someday list.
