### ISSUE TITLE
Ability Insert stacks settings into <head>

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#772]
Right now I have SEO Helper that adds meta tags into head via some PHP trickery. It would be so much nicer if I did not have to resort to using PHP. I want the ability to insert HTML (with settings) into the head.

**Comment by joeworkman** [comment]
Any thoughts on this one? Ran into another case of wanting this today…

**Comment by yourhead** [comment]
i think you can right now, but there are limitations.

you can use a template with the `scope` set to `pageHeadAbove`
and then you can include settings that have their `scope` set to `page`

the idea is that since you're editing one single thing (the `<head>` tag) that you should really be using page scoped templates and settings to do it.

do you think there are a lot of cases where you'd want to expand that to use stack-scoped settings? why? what's the rational?

i'm not against it -- i just can't think of any solid reasons myself -- and would rather err on the side of preventing clutter in shared areas of the page.
