### ISSUE TITLE
Standard way to alert users

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#780]
In many stacks, I need to present some sort of warning to a user when some condition has been met. I use this for so many things. It could be nice to have a uniform way to do this. Some things are simple string comparisons but other use JS in preview to generate warnings.

**Comment by yourhead** [comment]
Can you give me a practical use case?

I think it's really really important to look at each specific use case and see if there's ANY way that the info can be presented to the user -- or the problem can be changed -- or the interaction can be simplified -- to avoid displaying a block of text to the user. Almost anything is better than a block of text. Only a small fraction of users will ever bother to read it. 95% will simply click the default button to dismiss the window as quickly as possible.

Info:  Like just presenting some sort of feedback. Usually there are much better ways than using an alert window. e.g. "3 is the maximum number of columns" -- would be better just to disable the + button. There are times for textual feedback, but they should be pretty rare.

Alert:  Letting the user know that some critical event has happened that will change the way they're using their software. e.g. "Updates are disabled because your computer is not connected to the internet."

Warning: Letting the user opt out of a critical and non-undoable operation: overwriting files, sharing with the public, deleting things that cannot be un-deleted. This should always provide a "Cancel" button to let the user change their mind.

**Comment by joeworkman** [comment]
Dup #732
