### ISSUE TITLE
Option to not allow partialing a stack

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#790]
For some stacks (most probably child stacks of a main stack, or the main stack itself), it does not make sense to partial them. The overall use case might be not working any more.
I would like to have a plist option to not partial a stack.

**Comment by yourhead** [comment]
i don't think this is the case. and further, partials are becoming a dominant design mechanism within stacks.

i think if there is some use case where containment in a partial doesn't make sense, then you need to be more specific. perhaps instead of disabling partials entirely, the specifics of why that use case doesn't work well can be addressed more specifically.
