### ISSUE TITLE
Dark edit mode

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#792]
I like it dark 🤘
I guess you know what I want. Sure some stacks might need an edit mode css Adaption if they are fiddeling with edit mode css.

**Comment by yourhead** [comment]
i've separated dark mode support into 3 stages -- because it's a lot of work and it will probably come across several releases in stages -- and i'll be closing this bug in favor of those:

basic compatibility (not dark, but not broken): #823
dark mode (everything except the content edit area): #824
full dark (edit area too): #825
