### ISSUE TITLE
Cache busting parameters to images

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#804]
RapidWeaver has the ability to add query string parameters to the end of JS and CSS files that the get added to the page. The unique ID on the parameter changes when you republish the site. This way, cached files can then be re-cached by the browser or Cloudflare. 

What if this same thing was added to images as well? One tricky bit would be that if the same image was used across several pages, it would be nice if the query string was the same on both.

**Comment by yourhead** [comment]
would that be used much?  
i mean, the reason we do that with CSS and JS files is that those files CHANGE -- they're mutable.

but images are (mostly) immutable.

there are definitely some corner cases where images do change content:
 - user changes compression settings to a jpeg.
 - the image content is changed in another app, but the name is kept.

but both of those are relatively rare.


usually we want to optimize for the 80% case. but that would be optimizing for the 0.05% case.



if there are other use-cases for this that make it interesting maybe we can think of a way to solve the problem for just that case -- instead of burdening all images with that added extra complexity.

**Comment by yourhead** [comment]
yeah...   i've thought about this some more.  this is a really rare corner case.

 - any image that's dragged in as new gets a uniqueID -- so is cache busted by default
 - any image that is resized is exported with the size in its name, changing it's size changes the name -- so it's cache busted
 - change of format from png to jpeg, that changes the name too -- busted
 - a stack could export a transformed image and override the name it's exported as -- however in that case the stack developer has full control so it's out of my hands.
 - the user has overridden the name of the exported file -- forcing it not to rename in the resizing case -- but in that case the user is specifically requesting a URL -- and i'm betting they would get upset if I started slapping on extra cache-busting detritus to the end.
this basically only leaves changes that don't change the size of the image (shadow/border/etc) and cases where 

there are a few other corner cases, but they start getting really exotic and rare.
i think those cases are just too few to merit adding special cache-busting URLs.

but i'm all ears.  if there is some special case i haven't thought of that's important and causing confusion -- by all means let me know. i think from there we would just take it case-by-case to determine what the best way to improve that use-case is.
