### ISSUE TITLE
Tooltip for each multi-control

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#806]
It would be nice if each component with a multi-control could have its own tooltip. 

button-2/3/4
number-2/3/4
Etc

**Comment by yourhead** [comment]
I believe I've closed several similar requests already -- or at least discussed this with other devs.

What you are suggesting would actually be **easier** to do than what is currently implemented.  In other words, I consider it a **feature** that there is only one tooltip.

The reason is that I wanted to **strongly** discourage the use of multi-controls for simply packing lots of unrelated controls into a smaller space.  That would be ***a very bad thing*** for many and varied reasons that I won't bother explaining.

The current implementation has only a single title and a single tooltip to encourage developers to only use multi-controls for things that are very very closely related.  The subtitle adds a tiny bit of extra info to identify each of the different components.

The idea is that if a title, four identifiers (subtitles), and a tooltip are not enough to help the user figure out how to use these controls, then it's a pretty strong indication that the controls maybe shouldn't be packed so tightly together.

I've added (quite a bit actually) of extra code to make controls work this way over their basic default of simply having a title/subtitle/tooltip for each.  Your job as the feature requester is to convince me that your way is going to help users significantly more.  Or why the current system is hurting users in some way I'm not aware of.
