### ISSUE TITLE
Add alignment setting to Header

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#831]
It would be nice if there were alignment optinos in the default header stack. Many times people want to center a header and this is tough to do with the default header stack.

**Comment by yourhead** [comment]
That would require overriding the theme styling of the H1-6 tags. Is that wise? Seems unwise to me. I try hard to steer people away from using RW like a MS Word -- manually adjusting the style of each thing.

What would be great is if there were options to allow users to tweak there themes in that way.

Maybe I should write a plugin that does that.  😝

**Comment by joeworkman** [comment]
Easy. 4 buttons. 
* inherit
* left
* center
* right

By default it will inherit the theme styles.

**Comment by yourhead** [comment]
I feel like you didn't even read what I wrote. I'm not concerned about the UI at all. Or the difficulty of doing this (it would take less time to add this feature than to type this response to you). I didn't comment on that stuff at all.

It's a matter of encouraging users to manually override a theme's behavior whenever they want the theme to be slightly different.

Otherwise we're back to the way that people use Styled Text:  they manually adjust the style of each line that they want to be different from the theme. Which we all know is absolutely terrible -- it create sites that are full of thousands of repetitive inline styles that could be replaced by just a few lines of simple CSS in a site-wide, read-once-cached-for-all-pages theme css file.

I can see how that would be useful in one specific (and probably very much the minority) use case:  namely when the designer wants to diverge from the theme in a one-off special case.  That's fine and an override would be useful to the guy that needs to do that -- but by I'm unwilling to encourage 90% of the users to do the wrong thing, just to make that 10% case a little bit easier.  Especially for a built-in component that's heavily used.

I think the right thing to do is leave the built-in components as pure and simple and clean and "correct" as possible and let special cases be handled by 3rd party stacks.

And if the user doesn't want to install another stack to do that, I'd suggest that user use Styled Text or, if they're able, CSS to create the one-off style.  That's the right thing to do.

**Comment by joeworkman** [comment]
I read your comment. You were concerned about overwriting theme styles. If the inherit is used in my scneario, then no CSS properties would be added at all. Only if the user selected any of the other alignment options, it would add the appropriate CSS (or classes). This would provide 100% backwards compatibility and play nice with themes.

**Comment by joeworkman** [comment]
I just thought that this would be a quick win that I feel users would appreciate.
