### ISSUE TITLE
generalized way of adding library load lines to the header that are shared between all stacks on the page

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#85]
I have many stacks that use shared libraries. It would be awesome if I could ensure that a particular template was only loaded once across different stacks. 

isaiah:  see private list (allow collisions on scoped templates)

**Comment by yourhead** [comment]
i'm going to say "no" on this one without more specific detail.

the requirement is that each stack stand completely on its own so that updates/installs can happen smoothly.

e.g.: when a stack is swapped out for a new version, everything that the stack does will move to the new version -- no parts can be hanging out in other stacks or other places in RW.

but...

i an see that perhaps some things (like big JS libraries) maybe could loaded only once across multiple stacks -- shared assets.

**Comment by joeworkman** [comment]
We talked about this before and you had agreed to it before. Basically its like the behavior to assets. They will collide with each other potentially. So this is not completely new behavior. I don't recall the exact solution that we had come up with... I think that it was a new flag for templates. If that flag was set then the name of the file was used as the key.

**Comment by yourhead** [comment]
ok.  i know what this is then.  i have the whole conversation saved.  :-)

**Comment by joeworkman** [comment]
Score!

**Comment by yourhead** [comment]
Here are lots more details and a complete example on using this API
https://github.com/yourhead/VelocityDemo
