### ISSUE TITLE
SASS support for generating CSS files

### ISSUE THREAD

**Issue by jrondorf** [yourhead/s3#9]
Feature Request: Include a SASS preprocessor in order to generate CSS files.

**Comment by joeworkman** [comment]
Maybe? BOOO!

**Comment by yourhead** [comment]
still 100% convinced this is a good thing. it adds a compile step to the edit mode preview -- something that really is slow enough already.

i'm going to add it as-is and we can evaluate the performance. but i'm thinking that it might be best if we reserve this only to sass files assets that are compiled once right at export -- like the way we handle php.

that said, i have the basics working. however getting preview paths working correctly within the stack bundle is another thing entirely.

**Comment by yourhead** [comment]
notes about @import.  since sass does its own file search for @import and its own file reading there is no way for me to cache the content of @import. that means that every time an @import is used the files are found, read, compiled, etc. that's a very slow process. so this means a few things:
- using sass in edit mode should use as few @imports as possible.
- you cannot use stacks templates (e.g. %id%) in @imports.

**Comment by yourhead** [comment]
my overall gut feeling on libsass is that it's probably too slow to be of use on anything but very small css files -- and since very small css files don't benefit a huge amount from sass, there may not be very much practical use.

but… we'll give it a try.
